### ISSUE TITLE
Single Task only

### ISSUE THREAD

**Issue by KoolKeith** [umaranis/TaskScheduler#2]
Hello umaranis,
thank you very much for doing this. Very elegant design.
But I have a question. What is the proper ("right") way to: 

  **add a one-time, non-recurring Task ?**

I plan to use one-time-tasks exclusively in my scenario (timers for my Heating at home).

```
        // ----------------------- simulate Thermostat behaviour --------------------------------
        private void workSlowAndAnswer(int delaySeconds, string finalConstructedResponse)
        {
            TaskScheduler.ITask task = new TaskScheduler.RecurringTask(
                () => {
                    System.Threading.Thread.Sleep(300);
                    debCounter++;
                    BeginInvoke(new Action(delegate {
                        textBox1.AppendText($"Single task {taskNumber} complete. Publishing now response [{finalConstructedResponse}]{Environment.NewLine}");
                        client.Publish(myPubChannel, Encoding.UTF8.GetBytes(finalConstructedResponse), MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, true);
                    }));
                },
                DateTime.Now.AddSeconds(delaySeconds),  
                TimeSpan.Zero                           // <------  THE RIGHT TRICK ????
                );
            task.TaskId = taskNumber;
            schedular.AddTask(task);
            taskNumber = (int.Parse(taskNumber) + 1).ToString();

            if (!schedular.Started)
            {
                schedular.Start();
            }
            
        }
```

![image](https://user-images.githubusercontent.com/10271212/101992911-cadb0d80-3cb6-11eb-9515-e06a49755463.png)

**Comment by umaranis** [comment]
Exactly, that's the trick 👍 Setting the recurrence to TimeSpan.Zero.

**Alternatively, you can use `public void AddTask(Action taskAction, DateTime startTime)` rather than `public void AddTask(ITask task)`. This overload doesn't ask for the recurrence time span.**

Good to hear that you like the design. Do let me know if you run into any issues, I will be happy to help.

@KoolKeith

**Comment by KoolKeith** [comment]
Cool, thank you very much, I will try it out. 
Once all is running, I'll give you feedback of my longest achieved uptime (hopefully the whole heating season) of the service! Maybe it's a good scenario to test on, because it will run on a bit odd system: Linux Mint Sarah, "NUC", Mono (not even dot-net-core)

**Comment by umaranis** [comment]
Sounds good 👍 

All the best for your project @KoolKeith
