### ISSUE TITLE
Question about max wait time of 15 minutes in TaskScheduler

### ISSUE THREAD

**Issue by Aleksey-Kudryavtsev** [umaranis/TaskScheduler#3]
Hello @umaranis!
Great project,

This is not a bug, but I haven't found how to contact you in other way.

Do you remember why in TaskScheduler when it's waiting for the next task you limited the max wait time to 15 minutes?

       TimeSpan min15 = TimeSpan.FromMinutes(15);
       if (waitTime > min15) waitTime = min15; 

Does it have to do with how WaitOne works?

Thanks,
Aleksey

**Comment by umaranis** [comment]
Hi @Aleksey-Kudryavtsev ,

Good question...

When the task runner picks up the next task to execute and that task is scheduled to run in the future, it goes into waiting. The waiting period is equal to the time difference between the current time and the scheduled time of the task. But if that waiting period is over 15 minutes, the task runner waits for 15 minutes and then checks the queue again for how much it has to wait for.

Why 15 minutees? I found that if your PC goes to sleep that interferes with the WaitOne accuracy. To overcome this problem, the task runner never waits for more than 15 minutes and recalculates the wait time every 15 minutes if the next task is more than 15 minutes away in the future.

Hope this helps.
